### ISSUE TITLE
Procedure required to interface with 6x controller.

### ISSUE THREAD

**Issue by Bharathk-Gowda** [MitchBradley/Panel_FluidNC_UI#1]
Dear sir,

please provide procedure for hardware and software setup to integrate this 7”-esp32-HMI-Display with 6x controller.
It will be very helpful for beginners like me.

**Comment by MitchBradley** [comment]
The 7" display controller code and hardware wiring setup are not yet ready.  When we have finished with the design and implementation, we will provide the documentation.

Please consider sponsoring the FluidNC project so we can continue to work on the many aspects of this system which is available at no cost.
