### ISSUE TITLE
File type

### ISSUE THREAD

**Issue by lytke** [MitchBradley/Panel_FluidNC_UI#3]
File menu lists files ending on ".gcode" (lower case) only.
Gcode files ending on ".GCODE" are not shown.

File menu should ideally show all .gcode files regardless of lower/upper case.

**Comment by lytke** [comment]
Display issues the command "$Files/ListGCode" to FluidNC when entering files menu. 

As per documentation, this command lists only gcode files (.g .gc .gco .gcode .nc .ngc .ncc .txt .cnc .tap). http://wiki.fluidnc.com/en/features/commands_and_settings#fileslistgcodepath 

Changing this would require a major rework to handle output from a command like $LocalFS/List. 

Work around would be to point out this limitation with the user guide.  Closing issue as will not fix.

**Comment by MitchBradley** [comment]
https://github.com/bdring/FluidNC/pull/1412
